"""upgrade_models_user_post

Revision ID: 04
Revises: 03
Create Date: 2023-05-11 18:37:20.172864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04'
down_revision = '03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###
