"""4

Revision ID: f0e643a11ed5
Revises: d14e2bd75ded
Create Date: 2023-04-12 21:41:50.582958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e643a11ed5'
down_revision = 'd14e2bd75ded'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
